### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by Anahkiasen** [greenc/CookieMaster#1]
Hey, this is kind of a long shot but, bear with me. Didn't find any way to contact you so, this will do.

I recently took over the Cookie Monster development – more or less by force – because I was dissatisfied with the lack of updates and the overall low quality of the code.

So I started a **huge** refactor and performances overhaul – which is almost done. My point is to have something clean, tested, and easy to crawl through and extend so that people can make pull requests.

A few days in my rewrite I fell upon this repository (by checking who was hogging [all of rawgithub](https://rawgithub.com/stats.html) actually) and although Cookie Master isn't yet up to par feature-wise, I feel both my rewrite and your plugin were written with the same state of mind and intents.
So instead of you know, wasting both of our work on two similar but separate repositories, I wondered if you wanted to join me on the new Cookie Monster and join our forces and stuff ? I ask this and not the opposite because Cookie Monster, despite the state it was left in, is currently the most advanced in terms of features.

You can take a look at where I'm standing now by checking the sources of the repo, see if that helps maybe https://github.com/Anahkiasen/cookie-monster/tree/develop

Also you can check the original sources to, well, see what I started with https://github.com/Anahkiasen/cookie-monster/blob/develop/dist/js/original.js

**Comment by greenc** [comment]
Hey, sorry for the delay in getting back to you on this, but I've only just seen it (apparently I'm not getting notified of new issues - must fix that).

Shortly after releasing v.1.1.0 of Cookie Master, I stumbled upon your refactor-in-progress of Cookie Master. Obviously, it's a huge improvement on the monstrous source of the original, even if there's still some way to go before it's completely de-obfuscated and sane.

As it stands, I am not sure how to best respond to your proposal. On the one hand, I completely agree that having 2 separate plugins that have similar goals being maintained and developed separately is a waste of time and effort.

On the other hand, I've written CookieMaster from the ground up and as such have an intimate knowledge of the code base and a good plan for how to continue developing it.

You are right that it's not quite at feature parity with Cookie Monster just yet, although the only major feature that's missing currently is the building efficiency stuff, the main guts of which I will likely leverage from Frozen Cookies since the developer was nice enough to give full permission to reuse.

With all that said, I think for now I will continue to develop CookieMaster in situ, at least while I continue to have a reasonable amount of time to invest in the project.

I am more than happy to reevaluate things down the line, and certainly respect what you're achieved so far with your Cookie Monster rewrite - the original codebase left a lot to be desired!

Best,

Chris

**Comment by Anahkiasen** [comment]
Ok no worries, just though I'd ask o/
