### ISSUE TITLE
Season upgrades still don't appear in v1.16.2

### ISSUE THREAD

**Issue by shrx** [greenc/CookieMaster#54]
I updated to v1.16.2 and the icons for season upgrades do not appear, even though I had them before in this game. I updated from v1.15.2 directly to v1.16.2, maybe this is the problem?

**Comment by TheDutchman88** [comment]
make sure you have 5000 heavenly chips, and remember that you cannot activate the same season twice in a row.  so if you've just had christmas you will need to buy  haloween or valentines to make the christmas update available. If they still do not show up properly simply reset the game itself and they should reapear correctly.

**Comment by greenc** [comment]
If you went from the 1.15.x branch to 1.16.2 directly, you should not be affected. The original bug happened because CookieMaster attempted to simulate buying the seasonal upgrades, but neglected to suppress the function that hides them until the season time is up.

As of now, CookieMaster will explicitly blacklist all seasonal upgrades (as well as some others) from the simulation and auto-buy feature (which is fine since they have no BCI values anyway), so I'm pretty sure you should not get the bug.

Bear in mind that you need to have at least 5000 HC before the season switching upgrades appear.

**Comment by shrx** [comment]
@TheDutchman88 this is why I said I had the upgrades before. They disappeared when I refreshed the page and CookieMaster updated itself.

**Comment by greenc** [comment]
Closing this as I have tested extensively and cannot replicate the issue in a new/reset game using v1.16.2 and above.
