### ISSUE TITLE
Autobuy buys too much buildings.

### ISSUE THREAD

**Issue by TheDutchman88** [greenc/CookieMaster#57]
it appears that when there are enough cookies (that stay above lucky-frenzy) the autobuyer buys 4 buildings at once, instead of just 1 before checking what the next best BCI is.

found it odd that one of my upgrades had a BCI of 500.000.000 while the best BCI was just 98.000.000.. so i tested it by giving myself a few sextillion cookies to test the buyer, and it was buying 4 buildings in one go.

**Comment by shrx** [comment]
For me it seems to ignore the bank requirements even though I checked them in the settings. Not sure if this is the same issue.

**Comment by OlsonDev** [comment]
Not sure if 4 is the magic number but my Farms are ~`420Qa` whereas my my Time Machines are ~`116Qa`... and the majority of my other buildings are in the same boat; that is, substantially more expensive than my Time Machines. I think it's because I set my Wrinklers to `1 hour` auto-pop so when they pop, I have huge amounts of excess to spend.
