### ISSUE TITLE
CookieClicker v.1.0453 breaks lots of stuff

### ISSUE THREAD

**Issue by rashfael** [greenc/CookieMaster#78]
Orteil changed quite a lot with the last updates, and consequently broke almost every feature of CookieMaster. Will look for the sources, I suspect changed drawing routines as the first offender. I'll get a detailed look at it come Friday, help is of course welcome.

Firefox currently gives me a Syntax Error in CookieMaster.

**Comment by cope80** [comment]
Thank you for your work rash :)

**Comment by gcanu** [comment]
CookieMaster don't work for me with this version of CookieClicker

**Comment by Kenny85** [comment]
Thanks for spending so much time on fixing things! It is appreciated, just take your time.

**Comment by sranger** [comment]
Awesome! Glad you're on the job.

**Comment by inzanity** [comment]
I got it working somewhat with some changes, see diff at http://inz.fi/cookiemaster/cm-cc10453.diff although it still has issues, especially with tooltips.

**Comment by gcanu** [comment]
I began to work this morning on a fix. My solution is close to yours :

https://github.com/gcanu/CookieMaster/commit/b44909c2c0faffeb80a197d8eef79b1bec157f18#diff-0

2014-04-11 14:25 GMT+02:00 inzanity notifications@github.com:

> I got it working somewhat with some changes, see diff at
> http://inz.fi/cookiemaster/cm-cc10453.diff although it still has issues,
> especially with tooltips.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/greenc/CookieMaster/issues/78#issuecomment-40197855
> .

## 

Guillaume CANU
+++++++++[>+++++++>+
+++++++++++>++++<<<-
]>++.>+.>----.<<++++
++++.>>.<-----------
-.>.<++++++.--..++++
++.>.<<----------...

**Comment by rashfael** [comment]
Thanks for the solutions, guys. Nice fixes for the syntax error and the infinite santa presents.

I read the whole diff from the cookieclicker update on my trainride, and one important change is that each object now has its own tooltip method, which we can override/amend directly. This seems like a new and easier approach to enhance the tooltips, so we don't have to inject some html into the objects description. I'll test that and see if everything refreshes correctly.

**Comment by cope80** [comment]
I don't mean to sound like a noob, but how do we use the scripts that were posted?

**Comment by rashfael** [comment]
The posted diffs (differences between file versions) are just to show changes that could be made to the source code, and not really usable. While they fix certain bugs, not all functionality of CookieMaster is yet restored. I'll update the bookmarklet/userscript as soon as that is the case.

**Comment by cope80** [comment]
Oh ok, thanks :) Also thank you all for your work and contributions.

**Comment by rashfael** [comment]
I fixed the tooltips somewhat with an ugly hack (using setTimeout 1). To do this cleaner, I will restructure some code later. I want to avoid copypasting things around, but orteil uses the old non-dynamic tooltips for the upgrades, and the new ones with the tooltip function for the buildings, so the common code has to be restructured correctly.

**Comment by ghost** [comment]
you did a good job at fixing it and making things finally work haha :D two bugs that I notice right now are the tool tips (they keep flashing when ever I mouse over a building) though you are fixing that already, and then the other one is base cps after reset, its giving me a negative increase in what my cps would be if I was to reset right at the moment, other than those two I haven't really noticed any other bugs yet.

Edit: alright well found one other bug I guess lol, exiting any of the menus after being in them leaves the boxes where the buildings would be (the middle column) black a refresh seems to bring them back until you start messing with the menus again.. not really that big of a deal since most people don't stay outside of the menus for CMA anyways but just thought I'd let you know..

**Comment by cope80** [comment]
So excited to be able to use CM again. If you could post a bookmarklet once complete it would be very appreciated.

**Comment by ghost** [comment]
cope if you use greasemonkey/tampermonkey (depending on if you use chrome or FF) he has already updated the script to the latest working version.

**Comment by cope80** [comment]
I haven't used them before, but looks like its time to learn

**Comment by ghost** [comment]
if you use chrome, then tampermonkey would be the extension you would need to use and greasemonkey would be the one you'd use if you are on firefox. if you need any help setting anything up let me know and I'll try to help the best I can :)

**Comment by jkurs** [comment]
I tried using the greasemonkey method, but it still doesnt work. the only thing that I see that still works is some of the shorthand - ie instead of billion it displays B.

*\* oops didnt realize rashfael had his own version that wasnt hosted on the main site. It works perfect for me now, thank you! For people who got a little confused like I did, this was where I went and it worked. https://github.com/rashfael/CookieMaster/tree/selfhost#how-to-use

**Comment by rashfael** [comment]
The bookmarklet is also always loading the newest version, as long as you use the one on my branch with the correct url.

**Comment by gcanu** [comment]
Anyone has the source code of Cookie Clicker v.1.0411 ???

2014-04-12 9:31 GMT+02:00 rashfael notifications@github.com:

> The bookmarklet is also always loading the newest version, as long as you
> use the one on my branch with the correct url.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/greenc/CookieMaster/issues/78#issuecomment-40274098
> .

## 

Guillaume CANU
+++++++++[>+++++++>+
+++++++++++>++++<<<-
]>++.>+.>----.<<++++
++++.>>.<-----------
-.>.<++++++.--..++++
++.>.<<----------...
