### ISSUE TITLE
Cookie master not workin

### ISSUE THREAD

**Issue by lukksim** [greenc/CookieMaster#85]
I've installed the cookie master extension but nothing happened, didn't open the cookie master menu. Wat can i do?

**Comment by ImportSJC** [comment]
The current version of cookie clicker is not yet supported by cookie master, you should disable the cookie master extension until it is updated (there can be bugs if the version is not supported). its a bummer, i know, but the developer needs time to update since there are quite a few new features in the latest version!

**Comment by rashfael** [comment]
I have a fixed version [running over here](https://github.com/rashfael/CookieMaster/tree/selfhost#how-to-use)

**Comment by lukksim** [comment]
thanks man!

Date: Mon, 14 Apr 2014 10:18:25 -0700
