### ISSUE TITLE
Possible issue with cookie chain notice

### ISSUE THREAD

**Issue by raydawg2010** [greenc/CookieMaster#87]
According to CookieMaster I am eligible for #20 cookie chain which is worth 77.777 \* 10^18 but I never can get it because my cookie chain stops at #19.  After some confusion i dug into the code of Cookie Clicker to see what determines an end and the one I am getting failed on is 3 hours worth of cookie production.  By this formula, my 3 hours of production is roughly 4 \* 10^19 which is not very close to the minimum 77.777 \* 10^18 needed.  So there is something wrong with the Cookie Master calculation in that its telling me I qualify but in reality I do not.  

These are my current stats:
My CPS: 4,200,619,867,197,153 (by 3 hour production rule, i actually need around 7.2 \* 10^15)
Bank: 580,188,385,245,293,134,767

Edit:  According a member on the CC forums who helped me diagnose this issue, the CM uses a 6 hour production cap instead of a 3 hour cap.

**Comment by rashfael** [comment]
Currently I can't really say if any predictions are correct, since I currently only fix the bugs that are noticable (e.g. fly in your face when crashing). I will look into any errors that come to my attention. I expected some breaking update for easter, but that didn't happen.

CM seems to use this logic:
`chainValue < Game.cookies / 4 && chainValue < Game.cookiesPs * 60 * 60 * 6`

while CC uses this:
`Math.random()<0.01 || nextMoni>=Game.cookies*0.25 || nextMoni>Game.cookiesPs*60*60*3`

so the 6 hours seem clearly wrong and 3 hours worth of production correct.
I'll dig in some more to verify and then fix this.

**Comment by rashfael** [comment]
This has been fixed at last. Ticket can be closed.

**Comment by RuiApostolo** [comment]
hey, rashfael, sorry for the off-topic, but i have no idea how to reach you
other than this.
It has been a lot of time since greenc has been able to develop
CookieMaster. Is there any chance you can start developing new features on
your build, instead of just fixing bugs?

thanks!

**Comment by rashfael** [comment]
@super-aardwark is writing the latest bugfixes. I asked @greenc for permissions on this repo to manage issues and pull requests. As an alternative, an organization with a new repository could be created. As soon as the future of CookieMaster is cleared up I'll begin work on new features.
